const DB="r8R_DB_v1", STORE="videos";
let db, videos=[], currentId=null, page="home", query="", liked=new Set(JSON.parse(localStorage.r8rLiked||"[]")), history=JSON.parse(localStorage.r8rHistory||"[]"), subs=new Set(JSON.parse(localStorage.r8rSubs||"[]")), comments=JSON.parse(localStorage.r8rComments||"{}");

const $=s=>document.querySelector(s);
const toast=(m)=>{let t=$("#toast");t.textContent=m;t.classList.add("show");setTimeout(()=>t.classList.remove("show"),2200)};
function openDB(){return new Promise((res,rej)=>{let r=indexedDB.open(DB,1);r.onupgradeneeded=()=>r.result.createObjectStore(STORE,{keyPath:"id"});r.onsuccess=()=>{db=r.result;res()};r.onerror=()=>rej(r.error)})}
function all(){return new Promise((res,rej)=>{let q=db.transaction(STORE).objectStore(STORE).getAll();q.onsuccess=()=>res(q.result);q.onerror=()=>rej(q.error)})}
function put(v){return new Promise((res,rej)=>{let q=db.transaction(STORE,"readwrite").objectStore(STORE).put(v);q.onsuccess=()=>res();q.onerror=()=>rej(q.error)})}
function del(id){return new Promise((res,rej)=>{let q=db.transaction(STORE,"readwrite").objectStore(STORE).delete(id);q.onsuccess=()=>res();q.onerror=()=>rej(q.error)})}
const esc=s=>String(s??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));
const fmt=n=>n>=1e6?(n/1e6).toFixed(1)+"M":n>=1e3?(n/1e3).toFixed(1)+"K":String(n);
const age=ts=>{let s=Math.floor((Date.now()-ts)/1000);if(s<60)return s+"s ago";if(s<3600)return Math.floor(s/60)+"m ago";if(s<86400)return Math.floor(s/3600)+"h ago";return Math.floor(s/86400)+"d ago"};
function saveSets(){localStorage.r8rLiked=JSON.stringify([...liked]);localStorage.r8rSubs=JSON.stringify([...subs]);localStorage.r8rHistory=JSON.stringify(history);localStorage.r8rComments=JSON.stringify(comments)}
function sampleData(){return [
{id:"demo1",title:"Welcome to r8R",description:"Explore the r8R video platform.",tags:"#r8R #welcome",author:"r8R",category:"Technology",views:12480,likes:410,created:Date.now()-86400000*2,src:"",thumb:"",demo:true},
{id:"demo2",title:"Build Something Amazing",description:"A demo video card for your new channel.",tags:"#coding #build",author:"r8R Studio",category:"Technology",views:8230,likes:302,created:Date.now()-86400000*4,src:"",thumb:"",demo:true},
{id:"demo3",title:"Gaming Highlights",description:"Your next gaming upload can appear here.",tags:"#gaming #highlights",author:"R8 Gaming",category:"Gaming",views:19750,likes:920,created:Date.now()-86400000*6,src:"",thumb:"",demo:true}
]}
function card(v){let likedNow=liked.has(v.id);return `<article class="card"><div class="thumb" data-watch="${v.id}">${v.thumb?`<img src="${v.thumb}" alt="">`:`<div style="height:100%;display:grid;place-items:center;font-size:48px;font-weight:900;color:#198cff">r8R</div>`}<span class="play">▶</span></div><div class="meta"><div class="mini-avatar">${esc((v.author||"R")[0])}</div><div><h3>${esc(v.title)}</h3><p>${esc(v.author)} · ${fmt(v.views||0)} views · ${age(v.created)}</p><div class="tags">${esc(v.tags||"")}</div></div></div></article>`}
function render(list=videos){let filtered=list.filter(v=>v.visibility!=="Private"||v.author==="You");if(query)filtered=filtered.filter(v=>(v.title+" "+v.description+" "+v.tags+" "+v.author).toLowerCase().includes(query.toLowerCase()));
if(page==="trending")filtered=[...filtered].sort((a,b)=>(b.views||0)-(a.views||0)); if(page==="liked")filtered=filtered.filter(v=>liked.has(v.id)); if(page==="history")filtered=filtered.filter(v=>history.includes(v.id)); if(page==="subscriptions")filtered=filtered.filter(v=>subs.has(v.author)); 
$("#main").innerHTML=`<section class="hero"><p class="eyebrow">VIDEO • COMMUNITY • CREATORS</p><h1>${page==="home"?"Welcome to r8R":page[0].toUpperCase()+page.slice(1)}</h1><p>Upload, discover and watch videos with a clean blue-and-dark experience.</p><div class="chips">${["All","Gaming","Music","Technology","Entertainment","Education"].map(x=>`<button class="chip" data-cat="${x}">${x}</button>`).join("")}</div></section><div class="section-title"><h2>${query?`Results for “${esc(query)}”`:"Recommended"}</h2><span class="muted">${filtered.length} videos</span></div>${filtered.length?`<div class="grid">${filtered.map(card).join("")}</div>`:`<div class="empty"><h2>No videos here yet</h2><p>Upload a video or change your search/filter.</p><button class="primary" id="emptyUpload">Upload a video</button></div>`}`;
document.querySelectorAll("[data-watch]").forEach(x=>x.onclick=()=>watch(x.dataset.watch));document.querySelectorAll("[data-cat]").forEach(x=>x.onclick=()=>{let c=x.dataset.cat;render(c==="All"?videos:videos.filter(v=>v.category===c))});$("#emptyUpload")?.addEventListener("click",()=>show("uploadModal"))}
function show(id){$("#"+id).classList.add("show")} function hide(id){$("#"+id).classList.remove("show")}
async function watch(id){let v=videos.find(x=>x.id===id);if(!v)return;currentId=id;if(!history.includes(id)){history.unshift(id);history=history.slice(0,100);saveSets()}if(v.demo){$("#player").removeAttribute("src");$("#player").poster="";}else $("#player").src=v.src;
$("#watchInfo").innerHTML=`<h2 class="watch-title">${esc(v.title)}</h2><p class="muted">${esc(v.author)} · ${fmt(v.views||0)} views · ${age(v.created)}</p><div class="watch-actions"><button id="likeBtn" class="${liked.has(id)?"active":""}">♡ ${v.likes||0}</button><button id="subBtn" class="${subs.has(v.author)?"active":""}">★ ${subs.has(v.author)?"Subscribed":"Subscribe"}</button><button id="shareBtn">↗ Share</button>${v.author==="You"?`<button id="deleteBtn">Delete</button>`:""}</div><p>${esc(v.description)}</p><p class="tags">${esc(v.tags)}</p><h3>Comments</h3><div class="comment-box"><input id="commentInput" placeholder="Add a comment"><button class="primary" id="commentBtn">Post</button></div><div id="comments">${(comments[id]||[]).map(c=>`<div class="comment"><b>${esc(c.name)}</b><div>${esc(c.text)}</div></div>`).join("")}</div>`;
show("videoModal");
$("#likeBtn").onclick=async()=>{if(liked.has(id)){liked.delete(id);v.likes=Math.max(0,(v.likes||0)-1)}else{liked.add(id);v.likes=(v.likes||0)+1}saveSets();await put(v);watch(id);render()};
$("#subBtn").onclick=()=>{subs.has(v.author)?subs.delete(v.author):subs.add(v.author);saveSets();watch(id)};
$("#shareBtn").onclick=async()=>{let u=location.href.split("#")[0]+"#watch="+encodeURIComponent(id);try{await navigator.clipboard.writeText(u);toast("Video link copied")}catch{prompt("Copy this link:",u)}};
$("#commentBtn").onclick=()=>{let inp=$("#commentInput");if(!inp.value.trim())return;(comments[id]??=[]).push({name:"You",text:inp.value.trim()});inp.value="";saveSets();watch(id)};
$("#deleteBtn")?.addEventListener("click",async()=>{if(confirm("Delete this video?")){await del(id);videos=videos.filter(x=>x.id!==id);hide("videoModal");render()}});
}
$("#uploadBtn").onclick=()=>show("uploadModal");$("#themeBtn").onclick=()=>{document.body.classList.toggle("light");localStorage.r8rLight=document.body.classList.contains("light")};$("#menuBtn").onclick=()=>$("#sidebar").classList.toggle("hidden");
document.querySelectorAll("[data-close]").forEach(b=>b.onclick=()=>hide(b.dataset.close));
$("#videoFile").onchange=e=>$("#fileName").textContent=e.target.files[0]?.name||"Choose a video";
$("#uploadForm").onsubmit=async e=>{e.preventDefault();let file=$("#videoFile").files[0],thumb=$("#videoThumb").files[0];if(!file)return;let src=URL.createObjectURL(file), thumbUrl=thumb?URL.createObjectURL(thumb):"";let v={id:"v_"+Date.now(),title:$("#videoTitle").value.trim(),description:$("#videoDescription").value.trim(),tags:$("#videoTags").value.trim(),author:"You",category:$("#videoCategory").value,visibility:$("#videoVisibility").value,views:0,likes:0,created:Date.now(),src,thumb:thumbUrl,name:file.name};await put(v);videos.push(v);e.target.reset();$("#fileName").textContent="MP4, WebM, MOV and other browser-supported formats";hide("uploadModal");toast("Video published");page="home";render()};
$("#searchForm").onsubmit=e=>{e.preventDefault();query=$("#searchInput").value.trim();page="home";render()};
document.querySelectorAll(".nav").forEach(n=>n.onclick=()=>{document.querySelectorAll(".nav").forEach(x=>x.classList.remove("active"));n.classList.add("active");page=n.dataset.page;query="";$("#searchInput").value="";render()});
$("#homeBtn").onclick=e=>{e.preventDefault();page="home";render()};$("#profileBtn").onclick=()=>{$("#main").innerHTML=`<div class="profile-panel"><h1>Your r8R profile</h1><div class="mini-avatar">R</div><h2>You</h2><div class="statrow"><div class="stat"><strong>${videos.filter(v=>v.author==="You").length}</strong><span class="muted">Uploads</span></div><div class="stat"><strong>${liked.size}</strong><span class="muted">Liked</span></div><div class="stat"><strong>${subs.size}</strong><span class="muted">Subscriptions</span></div></div><button class="primary" id="profileUpload">Upload video</button></div>`;$("#profileUpload").onclick=()=>show("uploadModal")};
$("#settingsBtn").onclick=()=>{$("#main").innerHTML=`<div class="settings"><h1>Settings</h1><label>Theme<select id="setTheme"><option value="dark">Dark + blue</option><option value="light">Light</option></select></label><button class="primary" id="clearData">Clear my local r8R data</button><p class="muted">This static GitHub Pages version stores uploads, likes, comments and history in your browser. It does not upload files to a shared server.</p></div>`;$("#setTheme").value=document.body.classList.contains("light")?"light":"dark";$("#setTheme").onchange=e=>{document.body.classList.toggle("light",e.target.value==="light");localStorage.r8rLight=e.target.value==="light"};$("#clearData").onclick=async()=>{if(confirm("Clear all local r8R uploads and activity?")){let tx=db.transaction(STORE,"readwrite");tx.objectStore(STORE).clear();await new Promise(r=>tx.oncomplete=r);localStorage.clear();location.reload()}}};
window.onhashchange=()=>{let m=location.hash.match(/^#watch=(.+)/);if(m)watch(decodeURIComponent(m[1]))};
(async()=>{if(localStorage.r8rLight==="true")document.body.classList.add("light");await openDB();videos=await all();if(!videos.length){videos=sampleData()}render();if(location.hash.startsWith("#watch="))watch(decodeURIComponent(location.hash.slice(7)))})();
